service: serveless-chat

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  #region: us-east-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "execute-api:*"
      Resource: 
        Fn::Join:
          - ''
          - - 'arn:aws:execute-api:*:*:'
            - Ref: 'WebsocketsApi'
            - '/*/*/*'

functions:
  run:
    handler: src/handler.run
    events: 
      - websocket:
          route: $connect
          # routeResponseSelectionExpression: $default
      - websocket:
          route: $disconnect
          # routeResponseSelectionExpression: $default
      - websocket: 
          route: $default
          routeResponseSelectionExpression: $default
      - websocket:
          route: 'doSomething'
          routeResponseSelectionExpression: $default